# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# This is the $all format; I am going through and marking items w/
# -- used and configured
# ** looks interesting
# XX no thanks

# format = """
#-- $username\
#-- $hostname\
# $localip\
# $shlvl\
# $singularity\
# $kubernetes\
#-- $directory\
# $vcsh\
# $fossil_branch\
# $fossil_metrics\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $hg_branch\
# $hg_state\
# $pijul_channel\
# $docker_context\
# XX $package\
# $c\
# $cmake\
# $cobol\
# $daml\
# $dart\
# $deno\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $fennel\
# $fortran\
# $gleam\
# $golang\
# $guix_shell\
# $haskell\
# $haxe
# $helm\
# $java\
# $julia\
# $kotlin\
# $gradle\
# $lua\
# $nim\
# $nodejs\
# $ocaml\
# $opa\
# $perl\
# $php\
# $pulumi\
# $purescript\
# --$python\
# $quarto\
# $raku\
# $rlang\
# $red\
# $ruby\
# $rust\
# $scala\
# $solidity\
# $swift\
# $terraform\
# $typst\
# $vlang\
# $vagrant\
# $zig\
# $buf\
# $nix_shell\
# $conda\
# $meson\
# $spack\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $azure\
# $nats\
# XX $direnv\
# $env_var\
# $mise\
# $crystal\
# $custom\
# $sudo\
# -- $cmd_duration\
# $line_break\
# $jobs\
# $battery\
# $time\
# --$status\
# $os\
# $container\
# $netns\
# XX $shell\
# --$character"""

# format = "$all"

format = """
$python$username$hostname $directory $git_branch$git_commit$git_state$git_metrics$git_status
$character"""

right_format = """$cmd_duration$status"""

[username]
style_user = 'bold green'
style_root = 'bold red'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
style='bold green'
format='[@$ssh_symbol$hostname]($style)'

[directory]
truncate_to_repo = false
style = 'bold blue'

[character]
success_symbol = '↪'
error_symbol = '↪'

[cmd_duration]
min_time = 1
show_milliseconds = true

[status]
disabled = false

[python]
# format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
format = '[(\($virtualenv\))]($style) '


# # $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\

[git_branch]
# format = 'on [$symbol$branch(:$remote_branch)]($style) '
format = '[$symbol$branch(:$remote_branch)]($style) '
style = ''

[git_metrics]
disabled = true

[git_status]
# format = '([$all_status$ahead_behind]($style))'
# Shortcut for$conflicted$stashed$deleted$renamed$modified$typechanged$staged$untracked
# Displays diverged, ahead, behind or up_to_date format string based on the current status of the repo.
format = '([($ahead_behind|)$all_status]($style))'
style = ''

# These were the variables I used for zsh-git-prompt
# ZSH_THEME_GIT_PROMPT_PREFIX="("
# ZSH_THEME_GIT_PROMPT_SUFFIX=")"
# ZSH_THEME_GIT_PROMPT_HASH_PREFIX=":"
# ZSH_THEME_GIT_PROMPT_SEPARATOR="|"
# ZSH_THEME_GIT_PROMPT_BRANCH=""
# ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[yellow]%}%{●%G%}"
# ZSH_THEME_GIT_PROMPT_CONFLICTS="%{$fg[red]%}%{✖%G%}"
# ZSH_THEME_GIT_PROMPT_CHANGED="%{$fg[cyan]%}%{+%G%}"
# ZSH_THEME_GIT_PROMPT_BEHIND="%{↓·%2G%}"
# ZSH_THEME_GIT_PROMPT_AHEAD="%{↑·%2G%}"
# ZSH_THEME_GIT_PROMPT_STASHED="%{$fg_bold[blue]%}%{⚑%G%}"
# ZSH_THEME_GIT_PROMPT_UNTRACKED="%{.%G%}"
# ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%}%{✔%G%}"
# ZSH_THEME_GIT_PROMPT_LOCAL=" L"
# ZSH_THEME_GIT_PROMPT_UPSTREAM_FRONT=" {%{$fg_bold[blue]%}"
# ZSH_THEME_GIT_PROMPT_UPSTREAM_END="%{${reset_color}%}}"

# conflicted
ahead = '↑·$count'
behind = '↓·$count'
diverged = '↑·$ahead_count↓·$behind_count'
# up_to_date = '[✔](green)'
untracked = '[.$count](cyan)'
stashed = '[⚑$count](bold blue)'
modified = '[✚$count](blue)'
staged = '[●$count](yellow)'
renamed = '[»$count](white)'
deleted = '[✘$count](red)'
# typechanged = ''

